namespace_dev: dev
namespace_release: release
application_name: nodejs-sample

sample_app_vars_dev:
  NAME: "{{ application_name }}"
  NAMESPACE: "{{ namespace_dev }}"
  SOURCE_REPOSITORY_URL: "https://github.com/welshstew/e2e-pipeline-sample.git"
  CONTEXT_DIR: "/nodejs-ex"
sample_app_vars_release:
  NAME: "{{ application_name }}"
  NAMESPACE: "{{ namespace_release }}"

sample_app_build_dev:
  NAME: "{{ application_name }}"
  NAMESPACE: "{{ namespace_dev }}"
  SOURCE_REPOSITORY_URL: "https://github.com/welshstew/e2e-pipeline-sample.git"
  CONTEXT_DIR: "/nodejs-ex"
  
openshift_cluster_content:
- object: Builds
  content:
  - name: Sample Node Build DEV
    template: "{{ playbook_dir }}/templates/build.yml"
    params_from_vars: "{{ sample_app_build_dev }}"
    namespace: "{{ namespace_dev }}"
    tags:
    - dev

- object: Deployments
  content:
  - name: Sample Node Application DEV
    template: "{{ playbook_dir }}/templates/node-dev.yml"
    params_from_vars: "{{ sample_app_vars_dev }}"
    namespace: "{{ namespace_dev }}"
    tags:
    - dev

  - name: Sample Node Application RELEASE
    template: "{{ playbook_dir }}/templates/node-release.yml"
    params_from_vars: "{{ sample_app_vars_release }}"
    namespace: "{{ namespace_release }}"
    tags:
    - release
