---

- name: "Clean up temporary inventory dir"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tmp_inv_dir }}"

- name: "Clean up temporary dependency dir"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tmp_dep_dir }}"

- name: Clean up temporary Jinja directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ jinja_tmp_dir.path }}"
